[package]
name = "animathed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = "0.16.7"
kdam = "0.3.0"
rand = "0.8.5"
